// <auto-generated />
using System;
using DiscussipediA.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DiscussipediA.Migrations
{
    [DbContext(typeof(discussipediaContext))]
    partial class discussipediaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("DiscussipediA.Models.Discussion", b =>
                {
                    b.Property<int>("DiscussionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("discussion_id");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.Property<int?>("SubjectId")
                        .HasColumnName("subject_id");

                    b.HasKey("DiscussionId");

                    b.HasIndex("SubjectId");

                    b.ToTable("discussion");
                });

            modelBuilder.Entity("DiscussipediA.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("post_id");

                    b.Property<string>("Content")
                        .HasColumnName("content")
                        .HasMaxLength(100)
                        .IsUnicode(false);

                    b.Property<DateTime?>("Datetime")
                        .HasColumnName("datetime")
                        .HasColumnType("datetime");

                    b.Property<int?>("DiscussionId")
                        .HasColumnName("discussion_id");

                    b.Property<string>("Username")
                        .HasColumnName("username")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("PostId");

                    b.HasIndex("DiscussionId");

                    b.ToTable("post");
                });

            modelBuilder.Entity("DiscussipediA.Models.Subject", b =>
                {
                    b.Property<int>("SubjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("subject_id");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasMaxLength(25)
                        .IsUnicode(false);

                    b.HasKey("SubjectId");

                    b.ToTable("subject");
                });

            modelBuilder.Entity("DiscussipediA.Models.Discussion", b =>
                {
                    b.HasOne("DiscussipediA.Models.Subject", "Subject")
                        .WithMany("Discussion")
                        .HasForeignKey("SubjectId")
                        .HasConstraintName("FK__discussio__subje__398D8EEE");
                });

            modelBuilder.Entity("DiscussipediA.Models.Post", b =>
                {
                    b.HasOne("DiscussipediA.Models.Discussion", "Discussion")
                        .WithMany("Post")
                        .HasForeignKey("DiscussionId")
                        .HasConstraintName("FK__post__discussion__3C69FB99");
                });
#pragma warning restore 612, 618
        }
    }
}
